site_name: "Regtest in a Pod"
repo_name: "regtest-in-a-pod"
repo_url: https://github.com/thunderbiscuit/regtest-in-a-pod

theme:
  name: material
  # logo: images/logo.png

  icon:
    logo: material/qrcode

  features:
    - navigation.instant
    - navigation.tracking
    # turn this on if you want nav bar links
    # - navigation.tabs 
  
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search

nav:
  - About: index.md
  - Install: install.md
  - Usage: usage.md
